### ISSUE TITLE
Online synchronization tests & issues! (Fixed in update v1.1.5)

### ISSUE THREAD

**Issue by rashidmoviestar** [stefanvranjes/Vig2Online#2]
So, I have been testing the synchronization of movement and such online with a dear friend  of mine Voper. There are a lot of ways to break the synchronization and my theory is that every time something happens on one player's end and does not happen to the other it will cause extreme jitter as seen in the video below:

https://youtu.be/qL2YYXsjiXg

These are just some tests we did and I am very sure there are a lot more stuff to test.
the tests are as follows:
1. Mud driving test 1, this involves driving in a straight line back and forth also doing slight turns.

2. Mud driving test 2, same concept as the first one but this time we incorporated sharp turns and that broke stuff as seen on the video.

3. Bridge driving test 1, same concept as Mud driving test 1 but on top of a bridge, it works as intended.

4. Bridge driving test 2, it was a part of Bridge driving test 1 but when the bus clipped through the bridge and fell in the water then spawned back outside of the mansion and then when I got close to it, it was obvious that something caused the jittering to happen.

5. Elevating platform test 1, my friend was using the bull's eye rockets to elevate the platform but only like 2 to 3 shots were synced on both of our screens and actually hit the platform, in his screen he elevated to the top and in my screen it showed that he was jittering all over the place but once I elevated the platform to the top in my screen the synchronization went back to normal.

6. Elevating platform test 2, same concept as bridge driving test but on an elevated platform, it works fine but when the vehicle drops from the platform you can see that it drops in slow motion i don't personally know why, maybe it's not synced?

7. Elevating platform test 3, this time we tried to flood the stage and it worked but we had to be very deliberate and ensure that every platform was raised on both players's end to achieve the desired result. 

8. Blue mortar causes jitter as seen on the video, my theory is that the flattened tire physics is not synced which causes that. 

9. Hill climbing test, some physics based stuff when driving over hills and such are possibly not synced which causes the jitter.

10. Bear hug mine test, when you bear hug and there is one player inside it's fine but more than one it becomes crazy.

11. Cow puncher combo, every time I miss a shot in my friend's screen it causes him to jitter in mine, it's really weird.

There are still more stuff to test like different weapon combos and how they behave but that's for another time. Hope this was useful in any way.

**Comment by stefanvranjes** [comment]
Thanks Rashid and Voper for this documentation.

SOLUTION:
1. It seems as though some important data is missing from being sent SERVER -> CLIENT.
2. It seems as though some important data is missing from being sent CLIENT -> SERVER.
3. I suspect this has to be a cause of physics movement (as you said) that is not being delivered, or even implemented yet.

I need to look deeper into the game structure, before changing any of the Client or Server code.
So expect this to be handled in the next (smaller) update, which is the v1.1.5

**Comment by stefanvranjes** [comment]
UPDATE V1.1.5 is now available.
Let me know, Rashid, if any of your points are still valid.
